
CREATE TABLE CLASS_INFO(
    CLASS_ID      BIGINT          NOT NULL,
    CLASS_NAME    VARCHAR(100),
    CLASS_NO      VARCHAR(20),
    PRIMARY KEY (CLASS_ID)
)ENGINE=INNODB
;



CREATE TABLE STUDENT_INFO(
    STUDENT_ID    BIGINT         NOT NULL,
    NAME          VARCHAR(20),
    GENDER        INT,
    STUDENT_NO    INT,
    CLASS_ID      BIGINT         NOT NULL,
    PRIMARY KEY (STUDENT_ID)
)ENGINE=INNODB
;

ALTER TABLE STUDENT_INFO ADD CONSTRAINT RefCLASS_INFO4
    FOREIGN KEY (CLASS_ID)
    REFERENCES CLASS_INFO(CLASS_ID)
;


